format = """
$directory\
$git_branch\
$git_status\
$fill\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = false
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[git_branch]
symbol = ''
format = '[on](white) [$symbol $branch ]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

